remote: true
hybrid: true
onsite: true

experienceLevel:
  internship: false
  entry: true
  associate: true
  mid-senior level: true
  director: false
  executive: false

jobTypes:
  full-time: true
  contract: false
  part-time: false
  temporary: true
  internship: false
  other: false
  volunteer: true

date:
  all time: false
  month: false
  week: false
  24 hours: true

positions:
  - Software engineer

locations:
  - Germany

distance: 100

company_blacklist:
  - wayfair
  - Crossover

title_blacklist:
  - word1
  - word2

location_blacklist:
  - Brazil

llm_model_type: "gemini"
llm_model: "gemini-1.5-flash"